"""new columns for share

Revision ID: 46fa5b5d2e6a
Revises: b36b6ee0c260
Create Date: 2024-06-27 23:16:36.260753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46fa5b5d2e6a'
down_revision: Union[str, None] = 'b36b6ee0c260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
