"""db state

Revision ID: 5d858bdac739
Revises: 7ad692ea3d62
Create Date: 2024-06-28 22:45:09.803346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d858bdac739'
down_revision: Union[str, None] = '7ad692ea3d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testing',
    sa.Column('testid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['testid'], ['users.id'], name='testing_testid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('testid', name='testing_pkey')
    )
    # ### end Alembic commands ###
