"""db state new

Revision ID: 736e412b6a38
Revises: 6fc578f728f0
Create Date: 2024-06-28 23:03:45.898517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '736e412b6a38'
down_revision: Union[str, None] = '6fc578f728f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testing',
    sa.Column('testid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['testid'], ['users.id'], name='testing_testid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('testid', name='testing_pkey')
    )
    # ### end Alembic commands ###
