"""new columns for share

Revision ID: 7ad692ea3d62
Revises: eb0e1e4051ca
Create Date: 2024-06-28 22:32:21.028267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ad692ea3d62'
down_revision: Union[str, None] = 'eb0e1e4051ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testing',
    sa.Column('testid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['testid'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('testid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testing')
    # ### end Alembic commands ###
